### ISSUE TITLE
PCB4: frequency measurement does not work well

### ISSUE THREAD

**Issue by Emile666** [Emile666/THD_Analyzer#3]
The idea was to measure the actual frequency of the signal generator and to put that on the LCD-display. However it does not work well for small signals and is kind of an hassle to get to work for all output values. In the end I decided to skip the actual frequency measurement (both in HW and SW) and to just display the chosen frequency on the display. This will probably be implemented in V0.15.

**Comment by bengtssk** [comment]
Is it possible to make that change "board-compatible", i.e. only change the software, with the earlier version? Already built the PCB but haven't programmed the PIC yet. IAR requires a business email do be downloaded btw, haven't got the time to solve this yet.

**Comment by Emile666** [comment]
Yes, SW updates will be backward compatible.

Sorry to hear about IAR, that used to be more flexible. It is very convenient to have a working uC, you can PM me, so we can have this sorted.

**Comment by Emile666** [comment]
The frequency detection needs to be redesigned. It needs to work from 20 Hz-200kHz and from 5mV to 5V. I made a couple of LT-Spice simulations and came up with the following design. First the rectified signal is limited by D1 and D2 (for large signals) and then sufficiently amplified (>500x) for the transistor to switch. It works as specified and the output (at collector of Q1) is a 0-5V signal for the uC. It does need a new PCB4 revision, but I wanted to do that anyway. I am probably going to put the selected frequency on the LCD-display (the v0.15 option) and the measured frequency on the seven-segment display. Thanks to [bengtssk](https://github.com/bengtssk) for all the excellent ideas!

![image](https://github.com/Emile666/THD_Analyzer/assets/19247239/8d3a4211-9c4a-49a6-b24b-1f5f3ce6b251)

**Comment by Emile666** [comment]
I am going to propose a hardware change: since the SYNC signal has a constant amplitude, approx. 5 Vpp, it is a better input for the frequency-counter than the MAIN.OUT signal. I will probably make an update of the uC PCB (PCB4) in the near future, PCB1 will not get an update anymore. For now, modify the hardware as follows:

**On PCB1 V0.30:**
- Desolder CON3 (UC_IO) box-header
- Use a sharp knife to disconnect pin 1 (bottom right pin as seen from top-layer) from GND on top-layer. There are 3 connections to GND, remove all three of them.
- Same for the 3 connections to GND on the bottom-layer.
- Check for discontinuity between GND and CON3-1 pin.
- Solder CON3 box-header back.
- Solder wire from CON1-SYNC pin to CON3-1.
- Check for discontinuity between GND and CON3-1 pin.

**On uC PCB (PCB4, v0.30):**
- Desolder IC4-14 from its pad and lift it up.
- Solder a wire from CON10-1 (bottom right pin as seen from top-layer, pin next to AD_MAIN pin) to R33 pad next to R32. R32 and R33 are located next to each other, solder the wire to one of the pads in the middle.

**Comment by Emile666** [comment]
With the SYNC mod described above and software version V0.26 (d8caa0111f6bea1d36648135a0f9217f8c42cf81) the frequency-counter is working as it should. Therefore I am going to close this issue.
